### ISSUE TITLE
Where would you add dummy datasets?

### ISSUE THREAD

**Issue by nicoapg** [open-vianu/vianu#4]
Issue: In order to run certain functions in your repository you need some basic data. It would be beneficial if users had by default a minimal dataset to test functions. this would be a "default" option in the functions.

**Comment by jaegglic** [comment]
Why don't we put it under tests/tools/<experiment>/data (e.g. tests/tools/tici/data) and then also implement a (integration)-test that actually uses the dummy data. If we want to use unit and integration tests we could do the same folder pattern (tests/tools/tici/unit and tests/tools/tici/integration). What do you think?😊

**Comment by nicoapg** [comment]
uh I actually like this idea a lot @alho94

**Comment by alho94** [comment]
Sounds really good @jaegglic 😃

**Comment by alho94** [comment]
I propose to move the `vianu/tools/x` one level up to `vianu/x` as there will be no further directory of the level tools.

**Comment by nicoapg** [comment]
We stay with the recommendation from @jaegglic for the dummy data and the integration tests

We stay with the recommendation from @alho94 for removing tools folder
