### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by jaegglic** [open-vianu/vianu#6]
Should we update python from >=3.9 (maintenance status: security | end of support 10/2025) to >=3.10 (maintenance status: security | end of support 10/2026) or even >=3.11 (maintenance status: security | end of support 10/2027). https://www.python.org/downloads/

As the latter is already quite mature, I would suggest to use 3.11 😊

**Comment by alho94** [comment]
Hi @jaegglic, addressed in [PR 9](https://github.com/open-vianu/vianu/pull/9).  @nicoapg If you agree, you are fee to approve the PR. 😄
